"""Add threshold column to supplies

Revision ID: d6f7b09ecd90
Revises: c0f5d2490e70
Create Date: 2025-04-02 14:18:03.205552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f7b09ecd90'
down_revision = 'c0f5d2490e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.drop_column('threshold')

    # ### end Alembic commands ###
